CREATE TABLE IF NOT EXISTS `TENANT_A` (
  `USER_ID` INT NOT NULL,
  `USER_NAME` VARCHAR(45) NOT NULL,
  `POINTS` INT NOT NULL,
  `SCALE`  INT NOT NULL,
  `COMPLETE` BOOLEAN NOT NULL,
  `COMMENTS` VARCHAR(50) NULL)
ENGINE = InnoDB;


CREATE TABLE IF NOT EXISTS `TENANT_B` (
  `USER_ID` INT NOT NULL,
  `USER_NAME` VARCHAR(45) NOT NULL,
  `POINTS` INT NOT NULL,
  `COMPLETE` BOOLEAN NOT NULL,
  `COMMENTS` VARCHAR(50) NULL)
ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS `TENANT_C` (
  `USER_ID` INT NOT NULL,
  `USER_NAME` VARCHAR(45) NOT NULL,
  `POINTS` INT NOT NULL,
  `COMMENTS` VARCHAR(50) NULL)
ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS `TENANT_D` (
  `USER_ID` INT NOT NULL,
  `USER_NAME` VARCHAR(45) NOT NULL,
  `COMMENTS` VARCHAR(50) NULL)
ENGINE = InnoDB;


CREATE TABLE IF NOT EXISTS `TENANT_TABLE` (
  `TENANT_ID` VARCHAR(10) NOT NULL,
  `TABLE_NAME` VARCHAR(45) NOT NULL,
  `TABLE_DESC` VARCHAR(80) NULL,
  PRIMARY KEY (`TENANT_ID`, `TABLE_NAME`))
ENGINE = InnoDB;


CREATE TABLE IF NOT EXISTS `TENANT_FIELDS` (
  `TENANT_ID` VARCHAR(10) NOT NULL,
  `TABLE_NAME` VARCHAR(45) NOT NULL,
  `FIELD_NAME` VARCHAR(45) NOT NULL,
  `FIELD_TYPE` VARCHAR(80) NULL,
  `FIELD_COLUMN` INT NOT NULL,
  PRIMARY KEY (`TENANT_ID`, `TABLE_NAME`, `FIELD_NAME`))
  ENGINE = InnoDB;


CREATE TABLE IF NOT EXISTS `TENANT_DATA` (
  `RECORD_ID` INT NOT NULL AUTO_INCREMENT=1000 ,
  `TENANT_ID` VARCHAR(10) NOT NULL,
  `TENANT_TABLE` VARCHAR(45) NULL,
  `STUDENT_ID`  VARCHAR(45) NULL,
  `STUDENT_NAME`  VARCHAR(45) NULL,
  `GRADER_NAME` VARCHAR(45) NULL,
  `COLUMN_1` VARCHAR(80) NULL,
  `COLUMN_2` VARCHAR(80) NULL,
  `COLUMN_3` VARCHAR(80) NULL,
  `COLUMN_4` VARCHAR(80) NULL,
  PRIMARY KEY (`RECORD_ID`, `TENANT_ID`));

// Tenant A

insert into TENANT_FIELDS( TENANT_ID, TABLE_NAME, FIELD_NAME, FIELD_TYPE, FIELD_COLUMN ) values
 ( 'TA', 'TENANT_A', 'USER_ID', 'INT', 1 ) ;
insert into TENANT_FIELDS( TENANT_ID, TABLE_NAME, FIELD_NAME, FIELD_TYPE, FIELD_COLUMN ) values
 ( 'TA', 'TENANT_A', 'USER_NAME', 'VARCHAR(45)', 2 ) ;
 insert into TENANT_FIELDS( TENANT_ID, TABLE_NAME, FIELD_NAME, FIELD_TYPE, FIELD_COLUMN ) values
 ( 'TA', 'TENANT_A', 'POINTS', 'INT', 3 ) ;
 insert into TENANT_FIELDS( TENANT_ID, TABLE_NAME, FIELD_NAME, FIELD_TYPE, FIELD_COLUMN ) values
 ( 'TA', 'TENANT_A', 'SCALE', 'INT', 4 ) ;
 insert into TENANT_FIELDS( TENANT_ID, TABLE_NAME, FIELD_NAME, FIELD_TYPE, FIELD_COLUMN ) values
 ( 'TA', 'TENANT_A', 'COMPLETE', 'BOOLEAN', 5 ) ;
 insert into TENANT_FIELDS( TENANT_ID, TABLE_NAME, FIELD_NAME, FIELD_TYPE, FIELD_COLUMN ) values
 ( 'TA', 'TENANT_A', 'COMMENTS', 'VARCHAR(50)', 6 ) ;

// Tenant B

insert into TENANT_FIELDS( TENANT_ID, TABLE_NAME, FIELD_NAME, FIELD_TYPE, FIELD_COLUMN ) values
 ( 'TB', 'TENANT_B', 'USER_ID', 'INT', 1 ) ;
 insert into TENANT_FIELDS( TENANT_ID, TABLE_NAME, FIELD_NAME, FIELD_TYPE, FIELD_COLUMN ) values
 ( 'TB', 'TENANT_B', 'USER_NAME', 'VARCHAR(45)', 2 ) ;
  insert into TENANT_FIELDS( TENANT_ID, TABLE_NAME, FIELD_NAME, FIELD_TYPE, FIELD_COLUMN ) values
 ( 'TB', 'TENANT_B', 'POINTS', 'INT', 3 ) ;
  insert into TENANT_FIELDS( TENANT_ID, TABLE_NAME, FIELD_NAME, FIELD_TYPE, FIELD_COLUMN ) values
 ( 'TB', 'TENANT_B', 'COMPLETE', 'BOOLEAN', 4 ) ;
  insert into TENANT_FIELDS( TENANT_ID, TABLE_NAME, FIELD_NAME, FIELD_TYPE, FIELD_COLUMN ) values
 ( 'TB', 'TENANT_B', 'COMMENTS', 'VARCHAR(40)', 5 ) ;




// Tenant C


insert into TENANT_FIELDS( TENANT_ID, TABLE_NAME, FIELD_NAME, FIELD_TYPE, FIELD_COLUMN ) values
 ( 'TC', 'TENANT_C', 'USER_ID', 'INT', 1 ) ;
 insert into TENANT_FIELDS( TENANT_ID, TABLE_NAME, FIELD_NAME, FIELD_TYPE, FIELD_COLUMN ) values
 ( 'TC', 'TENANT_C', 'USER_NAME', 'VARCHAR(45)', 2 ) ;
  insert into TENANT_FIELDS( TENANT_ID, TABLE_NAME, FIELD_NAME, FIELD_TYPE, FIELD_COLUMN ) values
 ( 'TC', 'TENANT_C', 'POINTS', 'INT', 3 ) ;
  insert into TENANT_FIELDS( TENANT_ID, TABLE_NAME, FIELD_NAME, FIELD_TYPE, FIELD_COLUMN ) values
 ( 'TC', 'TENANT_C', 'COMMENTS', 'VARCHAR(40)', 4 ) ;



// Tenant D
insert into TENANT_FIELDS( TENANT_ID, TABLE_NAME, FIELD_NAME, FIELD_TYPE, FIELD_COLUMN ) values
 ( 'TD', 'TENANT_D', 'USER_ID', 'INT', 1 ) ;
 insert into TENANT_FIELDS( TENANT_ID, TABLE_NAME, FIELD_NAME, FIELD_TYPE, FIELD_COLUMN ) values
 ( 'TD', 'TENANT_D', 'USER_NAME', 'VARCHAR(45)', 2 ) ;
  insert into TENANT_FIELDS( TENANT_ID, TABLE_NAME, FIELD_NAME, FIELD_TYPE, FIELD_COLUMN ) values
 ( 'TD', 'TENANT_D', 'COMMENTS', 'VARCHAR(40)', 3 ) ;